service: serverless-boilerplate

provider:
  name: aws
  runtime: nodejs10.x
  region: ${opt:region, 'us-east-1'}
  stage: ${opt:stage, 'local'}
  environment: ${file(./config/${self:provider.stage}.yml)}

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  serverless-offline:
    port: 4000

functions:
  status:
    handler: src/public/handler.status
    events:
      - http:
          path: /check
          method: post
